MESSAGE_DELIMITER = "\n"

SERVER_SOCKER_ENV_VAR = "SERVER_SOCKET_PATH"
SERVER_LOCK_ENV_VAR = "LOCK_FILE_PATH"
LOG_PIPE_ENV_VAR = "LOG_PIPE_PATH"


DEFAULT_SERVER_SOCKET = "/tmp/server_1.sock"
DEFAULT_SERVER_LOCK = "/tmp/server_1.lock"
DEFAULT_LOG_PIPE = "/tmp/log_server_1.pipe"
